### ISSUE TITLE
bluno M0 mainboard arduino board definition incomplete

### ISSUE THREAD

**Issue by machinehistories** [DFRobot/DFRobotDuinoBoard#3]
I am using nucDuino1.0.2 board definition. I get the following error often ------ _fatal error: wiring_private.h: No such file or directory._
This happens with any external library that uses spi or i2c so, for example, if you want to use a display with this board it won't work. For testing purposes you can try adafruit ssd1306 library which has both i2c and spi options. Neither will compile. This problem happens when trying to run many other libraries on this board.
I am having numerous issues when I attempt to upload to this board. I often get an error - _exit status 1
Error compiling for board Bluno M0 MainBoard_. I am using arduino 1.8.4. Is it possible to get an upgraded board definition with a working wiring_private.h saved in the nucduino/cores. The following error happens constantly -
__Warning: platform.txt from core 'DFRobot Boards' contains deprecated recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} "{build.path}/{archive_file}" "{object_file}", automatically converted to recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} "{archive_file_path}" "{object_file}"._ Consider upgrading this core._

**Comment by WeMakeIt1995** [comment]
@machinehistories 
Hi, have you try to reinstall SDK by arduino IDE?

**Comment by machinehistories** [comment]
Do you mean the IDE or is there something else I need to install. I've tried many versions of arduino from 1.6 to new beta version and all give errors with this board. Do you have a board and can you tell me how not to get errors if you managed to solve this problem.

**Comment by WeMakeIt1995** [comment]
@machinehistories 
can you find wiring_private.h in your SDK floder?
and what is your system?

**Comment by machinehistories** [comment]
@forKnowYou 
In the following path C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino there is a wiring_private.h. I am running windows 10 Pro.

**Comment by machinehistories** [comment]
@forKnowYou 
I just noticed you added a new zip 1.0.3. I will try this tonight.
I think the wiring_private.h error is because there is no wiring_private.h located in the following directory -
 C:\Users\jason\AppData\Local\Arduino15\packages\nucDuino\hardware\nucDuino\1.0.2\cores\NUC123.

This may already be fixed in the 1.0.3 but is it also possible to upgrade the core and correct the platform.txt file to resolve the following issue:
_Warning: platform.txt from core 'DFRobot Boards' contains deprecated recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} "{build.path}/{archive_file}" "{object_file}", automatically converted to recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} "{archive_file_path}" "{object_file}". Consider upgrading this core._

**Comment by machinehistories** [comment]
@forKnowYou 
I tried 1.0.3 and I still get the same errors.
Warning: platform.txt from core 'DFRobot Boards' contains deprecated recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} "{build.path}/{archive_file}" "{object_file}", automatically converted to recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} "{archive_file_path}" "{object_file}". Consider upgrading this core.
D:\dropbox\Dropbox\arduino_processing\arduino\libraries\arduino_636739\Adafruit_SPITFT.cpp:22:32: fatal error: wiring_private.h: No such file or directory

     #include "wiring_private.h"

                                ^

compilation terminated.

Multiple libraries were found for "SPI.h"
 Used: C:\Users\jason\AppData\Local\Arduino15\packages\nucDuino\hardware\nucDuino\1.0.3\libraries\SPI
 Not used: D:\dropbox\Dropbox\arduino_processing\arduino\libraries\SPI-master
Multiple libraries were found for "Wire.h"
 Used: C:\Users\jason\AppData\Local\Arduino15\packages\nucDuino\hardware\nucDuino\1.0.3\libraries\Wire
 Not used: D:\dropbox\Dropbox\arduino_processing\arduino\libraries\Wire-master
exit status 1
Error compiling for board Bluno M0 MainBoard.

**Comment by machinehistories** [comment]
@forKnowYou 
after upgrading to 1.0.3 do I need to also update the bootloader on the board. I tried putting in a generic wiring_private.h from another board but then it looks like I end up with many problems relating to C:\Users\jason\AppData\Local\Arduino15\packages\nucDuino\hardware\nucDuino\1.0.3\cores\NUC123\avr\pgmspace.h

**Comment by WeMakeIt1995** [comment]
@machinehistories 
There not has file wiring_private.h in our lib.
can you give us url which the lib you want to run? (I can't find Adafruit_SPITFT.cpp in my computer and Adafruit's git home. may be there is some way to compatible it)
or you can comment #include "wiring_private" and try again.

**Comment by machinehistories** [comment]
@forKnowYou 
It looks  like the Arduino environment does not use wiring.h file anylonger, it was updated to wiring_private.h. Perhaps you should replace all references to wiring.h with wiring_private.h. Here is an example library that doesn't work. https://github.com/adafruit/Adafruit_SSD1306 To be honest very few things work on this board with the current board definition.  Let me know what you think we can do to get this working.

**Comment by machinehistories** [comment]
@forKnowYou 
You can also try the neopixel library [](https://github.com/adafruit/Adafruit_NeoPixel). That will show many errors. I have been trying various things on my end but I think this board has some incompatibility issues. If you can tell me if it works with a different version of arduino I will gladly use it with that version. I would really like to see this board work.

**Comment by WeMakeIt1995** [comment]
@machinehistories 
I'm so sorry there is some compatibility problems, we will find some way to solve it and @ you.
By the way, if you can use i2c bus on your ssd1306 device and screen size is 128 * 64, you may can try another lib https://github.com/DFRobot/DFRobot_SSD1306 or  https://github.com/DFRobot/DFRobot_OLED12864  (support more function),
If your screen size not 128 * 64, please ask me your size and I can give you some suggests.

**Comment by machinehistories** [comment]
@forKnowYou Thanks it is a great board but the compatibility issues are considerable. Can you give me any suggestions on how to get neopixel library working. Also I tried to run some code that used square() but it wasn't recognized and gave errors. Can you tell me what core file would I add the square function to in the board definition. I don't mind hacking if you can give me any additional suggestions. I look forward to your answer and I really look forward to getting a fully functional board definition from you sometime soon. After your answer I won't bother you and I'll wait for the update. I also want to point out there is a beta for M0 boards for makecode [https://maker.makecode.com](url) it would be cool to see you guys add the dfrobot boards to the list of supported boaards. It's a great software and uses the uf2 bootloader.

**Comment by WeMakeIt1995** [comment]
@machinehistories 
on neopixel, you can modify Adafruit_NeoPixel.cpp by flow ways.
1. delete all PROGMEM character.
2. use this code to replay function sine8 and gamma8.
``` c
uint8_t Adafruit_NeoPixel::sine8(uint8_t x) const {
  //return pgm_read_byte(&_sineTable[x]); // 0-255 in, 0-255 out
  return _sineTable[x];
}

uint8_t Adafruit_NeoPixel::gamma8(uint8_t x) const {
  //return pgm_read_byte(&_gammaTable[x]); // 0-255 in, 0-255 out
  return _gammaTable[x];
}
```
on ssd1306 spi demo, still try to find some way to compatible.
by the way, you need unchecked Aggressively cache compiled core in arduino ide's preferences.

**Comment by machinehistories** [comment]
@forKnowYou 
I appreciate your suggestions and I do hope an upgrade is in store for this board. Please keep me posted. - jason
